# Generated by Django 5.2.16 on 2026-08-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_remove_membership_duration_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="duration_months",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
