# Generated by Django 5.2.16 on 2026-08-08 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0003_section_seat_grid_col_seat_grid_row_and_more"),
        ("memberships", "0003_membership_duration_months"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["seat", "status", "start_date", "end_date"],
                name="memberships_seat_id_c66a57_idx",
            ),
        ),
    ]
