# Generated by Django 5.2.16 on 2026-08-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0005_membership_payment_method_and_cash_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                (
                    "event_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-received_at",),
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("authorized", "Authorized"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["razorpay_order_id"], name="memberships_razorpa_bfdc5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="memberships_status_048fa8_idx"),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("razorpay_order_id", ""), _negated=True),
                fields=("razorpay_order_id",),
                name="uniq_payment_razorpay_order_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("razorpay_payment_id", ""), _negated=True),
                fields=("razorpay_payment_id",),
                name="uniq_payment_razorpay_payment_id",
            ),
        ),
    ]
