# Generated by Django 5.2.16 on 2026-08-04 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Confirmation"),
                            ("expiry_warning", "Expiry Warning"),
                            ("daily_reminder", "Daily Reminder"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=10
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="memberships.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
                "indexes": [
                    models.Index(
                        fields=["membership", "type", "sent_at"],
                        name="notificatio_members_7db6c8_idx",
                    )
                ],
            },
        ),
    ]
