# Generated by Django 5.2.16 on 2026-08-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="type",
            field=models.CharField(
                choices=[
                    ("confirmation", "Confirmation"),
                    ("cash_request", "Cash Request"),
                    ("expiry_warning", "Expiry Warning"),
                    ("daily_reminder", "Daily Reminder"),
                ],
                max_length=30,
            ),
        ),
    ]
