# Generated by Django 5.2.16 on 2026-08-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_aadhar_number_user_class_name_user_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="aadhar_number",
        ),
        migrations.AddField(
            model_name="user",
            name="aadhar_document",
            field=models.FileField(blank=True, null=True, upload_to="aadhar_docs/"),
        ),
    ]
