# Generated by Django 5.2.16 on 2026-08-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="accounts_au_user_id_7b1069_idx",
            old_name="audit_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="accounts_au_actor_e_e98aab_idx",
            old_name="audit_email_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="accounts_au_created_606b86_idx",
            old_name="audit_created_idx",
        ),
        migrations.RenameIndex(
            model_name="otpcode",
            new_name="accounts_ot_user_id_d1b30a_idx",
            old_name="otp_user_purpose_used_idx",
        ),
        migrations.RenameIndex(
            model_name="otpcode",
            new_name="accounts_ot_expires_2f08f4_idx",
            old_name="otp_expires_at_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_email_74c8d6_idx",
            old_name="user_email_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_is_emai_fb6e2c_idx",
            old_name="user_email_verified_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_role_2b136f_idx",
            old_name="user_role_active_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_date_jo_ff39bb_idx",
            old_name="user_date_joined_idx",
        ),
    ]
